# Generated by Django 5.0.3 on 2024-03-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_foodmodel_ratting'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/food'),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='ratting',
            field=models.CharField(max_length=5),
        ),
    ]
